import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: Record<string, string>;
}

const defaultLanguage: Language = 'uz';

const getInitialLanguage = (): Language => {
  if (typeof window !== 'undefined') {
    const savedLanguage = localStorage.getItem('language') as Language;
    return (savedLanguage === 'uz' || savedLanguage === 'ru' || savedLanguage === 'en') ? savedLanguage : defaultLanguage;
  }
  return defaultLanguage;
};

const translations: Record<Language, Record<string, string>> = {
  'uz': {
    'appName': 'Maydonuz',
    'heroTitle': 'Futbol maydonlarini qidirish va band qilish',
    'heroSubtitle': 'Toshkentdagi eng yaxshi mini-futbol maydonlari, narxlar va qulay vaqtlarni toping',
    'search': 'Maydonlarni qidiring...',
    'searchBtn': 'Qidirish',
    'map': 'Xarita',
    'list': 'Ro‘yxat',
    'fields': 'Maydonlar',
    'howItWorks': 'Qanday ishlaydi?',
    'fieldOwners': 'Maydon egalari',
    'business': 'Biznes',
    'login': 'Kirish',
    'register': 'Ro‘yxatdan o‘tish',
    'logout': 'Chiqish',
    'available': 'Mavjud',
    'notAvailable': 'Band',
    'booked': 'Band',
    'price': 'Narx',
    'perHour': 'so‘m/soat',
    'perHourShort': '/ soat',
    'size': 'O‘lcham',
    'rating': 'Reyting',
    'book': 'Band qilish',
    'email': 'Email yoki telefon',
    'password': 'Parol',
    'forgotPassword': 'Parolni unutdingizmi?',
    'noResults': 'Hech qanday maydon topilmadi',
    'tryOtherFilters': 'Boshqa tuman yoki filtrlarni tanlab ko‘ring',
    'networkError': 'Tarmoq xatoligi. Namuna ma‘lumotlar ko‘rsatilmoqda.',
    'loginSuccess': 'Muvaffaqiyatli kirildi!',
    'loginError': 'Kirish muvaffaqiyatsiz. Ma‘lumotlaringizni tekshiring.',
    'subtitle': 'Futbol maydonlarini tezroq band qiling',
    'heroDesc': 'Futbol maydonlarini qidirib, band qilish platformasi',
    'results': 'Natijalar',
    'averagePrice': 'O‘rtacha narx',
    'view': 'Ko‘rinish',
    'fieldsCount': 'ta maydon',
    'filtered': 'saralandi',
    'mapLoading': 'Xarita yuklanmoqda...',
    'resetMapCenter': 'Toshkent markaziga qaytish',
    'detailedFilters': 'Batafsil filtrlar',
    'clearFilters': 'Filtrlarni tozalash',
    'searchFiltersTitle': 'Qidiruv filtrlari',
    'region': 'Viloyat',
    'fieldType': 'Maydon turi',
    'district': 'Tuman',
    'selectRegion': 'Viloyatni tanlang',
    'selectFieldType': 'Maydon turini tanlang',
    'selectSize': 'O‘lchamni tanlang',
    'selectDistrict': 'Tumanni tanlang',
    'tashkentRegion': 'Toshkent viloyati',
    'samarkand': 'Samarqand',
    'fergana': 'Farg‘ona',
    'andijan': 'Andijon',
    'artificial': 'Sun‘iy maysa',
    'natural': 'Tabiiy chim',
    'modern': 'Zamonaviy arena',
    'indoor': 'Yopiq maydon',
    'mini': 'Mini-futbol',
    'futsal': 'Futzal',
    'standard': 'Standart maydon',
    'yunusabad': 'Yunusobod',
    'chilanzar': 'Chilonzor',
    'shayhantahur': 'Shayxontohur',
    'almazar': 'Olmazor',
    'retry': 'Qayta urinish',
    'ownerNotSpecified': 'Egasi ko‘rsatilmagan',
    'contact': 'Aloqa',
    'companyAddress': 'Toshkent shahri, Chilonzor tumani',
    'pages': 'Sahifalar',
    'home': 'Bosh sahifa',
    'about': 'Biz haqimizda',
    'guide': 'Qo‘llanma',
    'allRightsReserved': 'Barcha huquqlar himoyalangan.',
    'name': 'Ism',
    'confirmPassword': 'Parolni tasdiqlang',
    'editProfile': 'Profilni tahrirlash',
    'changePassword': 'Parolni o‘zgartirish',
    'oldPassword': 'Eski parol',
    'newPassword': 'Yangi parol',
    'save': 'Saqlash',
    'loginToViewPhone': 'Telefon raqamini ko‘rish uchun tizimga kiring',
    'loginRequiredTitle': 'Kirish talab etiladi',
    'dontHaveAccount': 'Akkauntingiz yo‘qmi? Ro‘yxatdan o‘tish',
    'alreadyHaveAccount': 'Akkauntingiz bormi? Kirish',
    'sortBy': 'Saralash',
    'selectSort': 'Saralash turi',
    'ratingDesc': 'Reyting bo‘yicha',
    'priceAsc': 'Narx: arzonroq',
    'priceDesc': 'Narx: qimmatroq',
    'bookingDetails': 'Bron tafsilotlari',
    'paymentSuccess': 'To‘lov muvaffaqiyatli amalga oshirildi!',
    'receiptTitle': 'To‘lov cheki',
    'selectDate': 'Kunni tanlang',
    'selectTime': 'Vaqtni tanlang',
    'payWith': 'orqali to‘lash',
    'paymentMethodLabel': 'To‘lov usuli',
    'bookingHistory': 'Mening bronlarim',
    'invoice': 'Chek / Kvitansiya',
    'cancelBookingBtn': 'Bronni bekor qilish',
    'status': 'Holati',
    'unpaid': 'To‘lanmagan',
    'paid': 'To‘langan',
    'cancelled': 'Bekor qilingan',
    'ownerPanel': 'Egalik paneli',
    'myFields': 'Mening maydonlarim',
    'addField': 'Yangi maydon qo‘shish',
    'incomingBookings': 'Kelgan buyurtmalar',
    'fieldName': 'Maydon nomi',
    'fieldNamePlaceholder': 'Maydon nomini kiriting',
    'address': 'Manzil',
    'addressPlaceholder': 'To‘liq manzilni kiriting',
    'pricePerHour': 'Soatbay narxi',
    'latitude': 'Kenglik (Latitude)',
    'longitude': 'Uzunlik (Longitude)',
    'imageUrl': 'Rasm havolasi (URL)',
    'saveField': 'Maydonni saqlash',
    'fieldAddedSuccess': 'Yangi maydon muvaffaqiyatli qo‘shildi!',
    'noFieldsYet': 'Sizda hali qo‘shilgan maydonlar yo‘q.',
    'noIncomingBookings': 'Kelgan buyurtmalar mavjud emas.',
    'shareTelegram': 'Telegram orqali ulashish',
    'shareTelegramText': 'Maydonuz orqali ajoyib futbol maydoni:',
    'copyAddress': 'Manzilni nusxalash',
    'copiedAddress': 'Manzil muvaffaqiyatli nusxalandi!',
    'copiedSuccess': 'Nusxalandi',
    'selectSlotFirst': 'Iltimos, avval vaqtni tanlang!',
    'fillRequiredFields': 'Iltimos, barcha zaruriy maydonlarni to‘ldiring.',
    'imageTooLarge': 'Rasm hajmi juda katta (maksimal 2MB)',
    'quickTags': 'Tezkor tanlov',
    'all': 'Barchasi',
    'topRated': '⭐ 4.5+ Reyting',
    'artificialGrass': 'Sun‘iy maysa',
    'affordable': 'Arzonroq',
    'openInMap': 'Xaritada ochish',
    'details': 'Batafsil / Bron qilish',
    'myBookings': 'Bronlarim',
    'profile': 'Profil',
    'navigation': 'Navigatsiya',
    'phoneLoginRequired': 'Telefon: Ro‘yxatdan o‘ting',
    'phoneLockNotice': 'Telefon raqamini ko‘rish uchun ro‘yxatdan o‘ting',
    'phoneDirectContact': 'Maydon egasi bilan to‘g‘ridan-to‘g‘ri bog‘lanish imkoniyati',
    'guestBannerTitle': 'Maydonlarni band qilish va telefon raqamlarni ko‘rish',
    'guestBannerSubtitle': 'Bepul ro‘yxatdan o‘ting va maydon egalari bilan to‘g‘ridan-to‘g‘ri bog‘laning',
    'registerToBookPrompt': 'Maydonni band qilish uchun ro‘yxatdan o‘ting',
    'registerToBookSub': 'Online band qilish va SMS kvitansiya olish uchun tizimga kiring',
    'loginToContinue': 'Maydoningizni qo‘shish uchun avval tizimga kiring yoki ro‘yxatdan o‘ting',
    'loadMore': 'Ko‘proq ko‘rsatish',
    'googleMapsNav': 'Google Xaritada navigatsiya',
    'cashPayment': 'Naqd pul',
    'bookAgain': 'Yana bron qilish',
    'howItWorksBadge': '3 bosqichda oson va tezkor',
    'howItWorksTitle': 'Maydonuz qanday ishlaydi?',
    'howItWorksSubtitle': 'Ortiqcha qo‘ng‘iroqlarsiz, atigi 1 daqiqada Toshkentdagi eng qulay maydonni toping, vaqtni tanlang va o‘yinni boshlang.',
    'step1Indicator': '1. Maydonni tanlash',
    'step2Indicator': '2. Vaqtni band qilish',
    'step3Indicator': '3. Futbol o‘ynash',
    'step1Badge': 'Tezkor saralash',
    'step1Title': '1. Maydonni tanlang',
    'step1Desc': 'Tuman, narx, maydon o‘lchami va qulayliklar (dush, yoritish) bo‘yicha o‘zingizga mos stadionni toping.',
    'tryDistrict': 'Tumanni sinab ko‘ring:',
    'clickToTest': 'bosing',
    'step2Badge': 'Jonli grafik',
    'step2Title': '2. Vaqtni belgilang',
    'step2Desc': 'Real vaqt rejimida bo‘sh soatlarni ko‘ring. Telefon qilib navbat kutmasdan, 1 marta bosishda band qiling.',
    'selectSlotHint': 'Bo‘sh vaqtni bosing:',
    'instantConfirm': 'Avtomatik tasdiqlash',
    'step3Badge': 'Match Pass',
    'step3Title': '3. Futbol o‘ynang!',
    'step3Desc': 'To‘lovni qulay usulda amalga oshiring, kvitansiyani do‘stlarga ulashing va o‘yinga boring!',
    'matchTicket': 'O‘yin chiptasi',
    'matchShare': 'Do‘stlarga ulashish',
    'ticketCopied': 'Ulashildi!',
    'ownerBadge': 'Maydon egalari va menejerlar uchun',
    'ownerHeroTitle': 'Futbol maydoningiz bormi? Uni daromadga aylantiring',
    'ownerHeroDesc': 'Bo‘sh soatlarni unuting. Maydoningizni Maydonuz platformasiga qo‘shing, har kuni yuzlab futbol havaskorlariga ko‘rining va tushumni 40% ga oshiring.',
    'ownerCtaPrimary': 'Maydoningizni bepul qo‘shing',
    'ownerFeature1Title': 'Bo‘sh soatlarni to‘ldirish',
    'ownerFeature1Desc': 'Kunduzgi va erta tongdagi bo‘sh qoladigan vaqtlarga ham mijozlar toping.',
    'ownerFeature2Title': 'Avtomatlashgan grafik',
    'ownerFeature2Desc': 'Buyurtmalar, to‘lovlar va bandlikni yagona qulay dashboardda boshqaring.',
    'ownerFeature3Title': '0% komissiya dastlabki oyda',
    'ownerFeature3Desc': 'Platformaga ulanish mutlaqo bepul, yashirin to‘lovlarsiz boshlang.',
    'revenueCalculatorTitle': 'Daromad kalkulyatori',
    'revenueCalculatorSubtitle': 'Maydoningiz Maydonuz orqali qancha daromad keltirishi mumkinligini hisoblang',
    'hourlyPriceLabel': 'Soatbay narx',
    'dailyHoursLabel': 'Kunlik o‘rtacha bandlik',
    'hoursPerDay': 'soat / kun',
    'potentialMonthlyIncome': 'Oylik kutilayotgan daromad',
    'revenueFormulaNote': 'Hisob-kitob 30 kunlik to‘liq oylik o‘rtacha bandlik asosida hisoblandi',
    'startEarningToday': 'Bugunoq daromadni boshlang',
    'nearestToMe': 'Menga eng yaqin',
    'sortByDistance': 'Masofa: eng yaqin',
    'distanceFromYou': 'Sizdan',
    'kmAway': 'km',
    'locating': 'Joylashuv aniqlanmoqda...',
    'locationFound': 'Joylashuvingiz aniqlandi!',
    'locationPermissionDenied': 'Geolokatsiyaga ruxsat berilmadi',
    'yourLocation': 'Sizning joylashuvingiz'
  },
  'ru': {
    'appName': 'Maydonuz',
    'heroTitle': 'Поиск и бронирование футбольных полей',
    'heroSubtitle': 'Лучшие футбольные поля Ташкента, актуальные цены и удобное время без звонков',
    'search': 'Поиск полей...',
    'searchBtn': 'Поиск',
    'map': 'Карта',
    'list': 'Список',
    'fields': 'Поля',
    'howItWorks': 'Как это работает?',
    'fieldOwners': 'Владельцам полей',
    'business': 'Бизнес',
    'login': 'Вход',
    'register': 'Регистрация',
    'logout': 'Выйти',
    'available': 'Доступно',
    'notAvailable': 'Занято',
    'booked': 'Занято',
    'price': 'Цена',
    'perHour': 'сум/час',
    'perHourShort': '/ час',
    'size': 'Размер',
    'rating': 'Рейтинг',
    'book': 'Забронировать',
    'email': 'Email или телефон',
    'password': 'Пароль',
    'forgotPassword': 'Забыли пароль?',
    'noResults': 'Поля не найдены',
    'tryOtherFilters': 'Попробуйте изменить район или параметры фильтра',
    'networkError': 'Ошибка сети. Отображаются примеры данных.',
    'loginSuccess': 'Вход выполнен успешно!',
    'loginError': 'Ошибка входа. Проверьте ваши данные.',
    'subtitle': 'Бронируйте футбольные поля быстрее',
    'heroDesc': 'Платформа для поиска и бронирования футбольных полей',
    'results': 'Результаты',
    'averagePrice': 'Средняя цена',
    'view': 'Вид',
    'fieldsCount': 'полей',
    'filtered': 'отфильтровано',
    'mapLoading': 'Карта загружается...',
    'resetMapCenter': 'Вернуться в центр Ташкента',
    'detailedFilters': 'Подробные фильтры',
    'clearFilters': 'Сбросить фильтры',
    'searchFiltersTitle': 'Фильтры поиска',
    'region': 'Область',
    'fieldType': 'Тип поля',
    'district': 'Район',
    'selectRegion': 'Выберите область',
    'selectFieldType': 'Выберите тип поля',
    'selectSize': 'Выберите размер',
    'selectDistrict': 'Выберите район',
    'tashkentRegion': 'Ташкентская область',
    'samarkand': 'Самарканд',
    'fergana': 'Фергана',
    'andijan': 'Андижан',
    'artificial': 'Искусственный газон',
    'natural': 'Натуральный газон',
    'modern': 'Современная арена',
    'indoor': 'Крытое поле',
    'mini': 'Мини-футбол',
    'futsal': 'Футзал',
    'standard': 'Стандартное поле',
    'yunusabad': 'Юнусабад',
    'chilanzar': 'Чиланзар',
    'shayhantahur': 'Шайхантахур',
    'almazar': 'Алмазар',
    'retry': 'Повторить попытку',
    'ownerNotSpecified': 'Владелец не указан',
    'contact': 'Контакты',
    'companyAddress': 'город Ташкент, Чиланзарский район',
    'pages': 'Страницы',
    'home': 'Главная',
    'about': 'О нас',
    'guide': 'Руководство',
    'allRightsReserved': 'Все права защищены.',
    'name': 'Имя',
    'confirmPassword': 'Подтвердите пароль',
    'editProfile': 'Редактировать профиль',
    'changePassword': 'Изменить пароль',
    'oldPassword': 'Старый пароль',
    'newPassword': 'Новый пароль',
    'save': 'Сохранить',
    'loginToViewPhone': 'Войдите, чтобы увидеть телефон',
    'loginRequiredTitle': 'Требуется вход',
    'dontHaveAccount': 'Нет аккаунта? Зарегистрироваться',
    'alreadyHaveAccount': 'Уже есть аккаунт? Войти',
    'sortBy': 'Сортировка',
    'selectSort': 'Выберите сортировку',
    'ratingDesc': 'По рейтингу',
    'priceAsc': 'Сначала дешевые',
    'priceDesc': 'Сначала дорогие',
    'bookingDetails': 'Детали бронирования',
    'paymentSuccess': 'Оплата прошла успешно!',
    'receiptTitle': 'Чек оплаты',
    'selectDate': 'Выберите день',
    'selectTime': 'Выберите время',
    'payWith': 'оплатить через',
    'paymentMethodLabel': 'Способ оплаты',
    'bookingHistory': 'Мои бронирования',
    'invoice': 'Чек / Квитанция',
    'cancelBookingBtn': 'Отменить бронь',
    'status': 'Статус',
    'unpaid': 'Не оплачено',
    'paid': 'Оплачено',
    'cancelled': 'Отменено',
    'ownerPanel': 'Панель владельца',
    'myFields': 'Мои поля',
    'addField': 'Добавить поле',
    'incomingBookings': 'Входящие брони',
    'fieldName': 'Название поля',
    'fieldNamePlaceholder': 'Введите название поля',
    'address': 'Адрес',
    'addressPlaceholder': 'Введите полный адрес',
    'pricePerHour': 'Цена за час',
    'latitude': 'Широта (Latitude)',
    'longitude': 'Долгота (Longitude)',
    'imageUrl': 'Ссылка на изображение (URL)',
    'saveField': 'Сохранить поле',
    'fieldAddedSuccess': 'Новое поле успешно добавлено!',
    'noFieldsYet': 'У вас пока нет добавленных полей.',
    'noIncomingBookings': 'Входящих броней пока нет.',
    'shareTelegram': 'Поделиться в Telegram',
    'shareTelegramText': 'Отличное футбольное поле на Maydonuz:',
    'copyAddress': 'Скопировать адрес',
    'copiedAddress': 'Адрес успешно скопирован!',
    'copiedSuccess': 'Скопировано',
    'selectSlotFirst': 'Пожалуйста, сначала выберите время!',
    'fillRequiredFields': 'Пожалуйста, заполните все обязательные поля.',
    'imageTooLarge': 'Размер изображения слишком большой (макс. 2МБ)',
    'quickTags': 'Быстрый выбор',
    'all': 'Все',
    'topRated': '⭐ Рейтинг 4.5+',
    'artificialGrass': 'Искусственный газон',
    'affordable': 'Доступные',
    'openInMap': 'Открыть на карте',
    'details': 'Подробнее / Бронь',
    'myBookings': 'Брони',
    'profile': 'Профиль',
    'navigation': 'Навигация',
    'phoneLoginRequired': 'Телефон: Регистрация',
    'phoneLockNotice': 'Зарегистрируйтесь, чтобы увидеть номер телефона',
    'phoneDirectContact': 'Прямая связь с владельцем поля без посредников',
    'guestBannerTitle': 'Бронирование полей и просмотр контактов',
    'guestBannerSubtitle': 'Зарегистрируйтесь бесплатно и связывайтесь с владельцами напрямую',
    'registerToBookPrompt': 'Зарегистрируйтесь для бронирования',
    'registerToBookSub': 'Войдите для онлайн-бронирования и получения SMS-чека',
    'loginToContinue': 'Войдите или зарегистрируйтесь, чтобы добавить свое поле',
    'loadMore': 'Показать еще',
    'googleMapsNav': 'Навигация в Google Maps',
    'cashPayment': 'Наличные',
    'bookAgain': 'Забронировать еще',
    'howItWorksBadge': 'Легко и быстро за 3 шага',
    'howItWorksTitle': 'Как работает Maydonuz?',
    'howItWorksSubtitle': 'Без лишних звонков, всего за 1 минуту найдите удобное поле в Ташкенте, выберите время и начните игру.',
    'step1Indicator': '1. Выбор поля',
    'step2Indicator': '2. Бронь времени',
    'step3Indicator': '3. Игра в футбол',
    'step1Badge': 'Быстрый подбор',
    'step1Title': '1. Выберите поле',
    'step1Desc': 'Найдите подходящий стадион по району, цене, размеру поля и удобствам (душ, парковка, освещение).',
    'tryDistrict': 'Попробуйте район:',
    'clickToTest': 'нажмите',
    'step2Badge': 'Живое расписание',
    'step2Title': '2. Выберите время',
    'step2Desc': 'Смотрите свободные часы в реальном времени. Бронируйте в 1 клик без ожидания на телефоне.',
    'selectSlotHint': 'Выберите свободное время:',
    'instantConfirm': 'Мгновенное подтверждение',
    'step3Badge': 'Матч Пасс',
    'step3Title': '3. Играйте в футбол!',
    'step3Desc': 'Оплатите удобным способом, отправьте приглашение друзьям и приходите на матч!',
    'matchTicket': 'Билет на матч',
    'matchShare': 'Поделиться с друзьями',
    'ticketCopied': 'Отправлено!',
    'ownerBadge': 'Для владельцев и менеджеров полей',
    'ownerHeroTitle': 'У вас есть футбольное поле? Превратите его в стабильный доход',
    'ownerHeroDesc': 'Забудьте о простаивающих часах. Подключите поле к Maydonuz, привлекайте сотни игроков ежедневно и увеличьте выручку до 40%.',
    'ownerCtaPrimary': 'Добавить поле бесплатно',
    'ownerFeature1Title': 'Заполнение свободных окон',
    'ownerFeature1Desc': 'Привлекайте игроков даже на утренние и дневные часы без простоя.',
    'ownerFeature2Title': 'Автоматизированный график',
    'ownerFeature2Desc': 'Управляйте бронями, графиком и платежами в едином личном кабинете.',
    'ownerFeature3Title': '0% комиссии в первый месяц',
    'ownerFeature3Desc': 'Подключение полностью бесплатно, начните без скрытых комиссий.',
    'revenueCalculatorTitle': 'Калькулятор дохода',
    'revenueCalculatorSubtitle': 'Рассчитайте потенциальный доход вашего поля через платформу Maydonuz',
    'hourlyPriceLabel': 'Цена за час',
    'dailyHoursLabel': 'Средняя занятость в день',
    'hoursPerDay': 'часов / день',
    'potentialMonthlyIncome': 'Ожидаемый доход в месяц',
    'revenueFormulaNote': 'Расчет основан на средней занятости за 30 дней',
    'startEarningToday': 'Начните зарабатывать сегодня',
    'nearestToMe': 'Ближайшие',
    'sortByDistance': 'Расстояние: ближайшие',
    'distanceFromYou': 'От вас',
    'kmAway': 'км',
    'locating': 'Определение геопозиции...',
    'locationFound': 'Ваша локация определена!',
    'locationPermissionDenied': 'Доступ к геолокации не предоставлен',
    'yourLocation': 'Ваша локация'
  },
  'en': {
    'appName': 'Maydonuz',
    'heroTitle': 'Find & Book Football Pitches',
    'heroSubtitle': 'Discover top football pitches across Tashkent with real-time availability and transparent pricing',
    'search': 'Search fields by name or area...',
    'searchBtn': 'Search',
    'map': 'Map',
    'list': 'List',
    'fields': 'Pitches',
    'howItWorks': 'How It Works',
    'fieldOwners': 'For Pitch Owners',
    'business': 'Business',
    'login': 'Log in',
    'register': 'Sign up',
    'logout': 'Log out',
    'available': 'Available',
    'notAvailable': 'Booked',
    'booked': 'Booked',
    'price': 'Price',
    'perHour': 'UZS/hour',
    'perHourShort': '/ hr',
    'size': 'Size',
    'rating': 'Rating',
    'book': 'Book Now',
    'email': 'Email or phone',
    'password': 'Password',
    'forgotPassword': 'Forgot password?',
    'noResults': 'No pitches found',
    'tryOtherFilters': 'Try changing your district or filter criteria',
    'networkError': 'Network error. Showing sample pitch data.',
    'loginSuccess': 'Signed in successfully!',
    'loginError': 'Sign in failed. Please verify your credentials.',
    'subtitle': 'Book football pitches in seconds',
    'heroDesc': 'Platform for discovering and booking football pitches',
    'results': 'Results',
    'averagePrice': 'Average Price',
    'view': 'View',
    'fieldsCount': 'pitches',
    'filtered': 'filtered',
    'mapLoading': 'Loading map...',
    'resetMapCenter': 'Reset to Tashkent Center',
    'detailedFilters': 'Detailed Filters',
    'clearFilters': 'Clear Filters',
    'searchFiltersTitle': 'Search Filters',
    'region': 'Region',
    'fieldType': 'Field Type',
    'district': 'District',
    'selectRegion': 'Select Region',
    'selectFieldType': 'Select Field Type',
    'selectSize': 'Select Size',
    'selectDistrict': 'Select District',
    'tashkentRegion': 'Tashkent Region',
    'samarkand': 'Samarkand',
    'fergana': 'Fergana',
    'andijan': 'Andijan',
    'artificial': 'Artificial Turf',
    'natural': 'Natural Grass',
    'modern': 'Modern Stadium',
    'indoor': 'Indoor Pitch',
    'mini': 'Mini Football',
    'futsal': 'Futsal',
    'standard': 'Standard Pitch',
    'yunusabad': 'Yunusabad',
    'chilanzar': 'Chilanzar',
    'shayhantahur': 'Shaykhantakhur',
    'almazar': 'Almazar',
    'retry': 'Retry',
    'ownerNotSpecified': 'Owner not specified',
    'contact': 'Contact',
    'companyAddress': 'Tashkent, Chilanzar district',
    'pages': 'Pages',
    'home': 'Home',
    'about': 'About Us',
    'guide': 'Guide',
    'allRightsReserved': 'All rights reserved.',
    'name': 'Name',
    'confirmPassword': 'Confirm Password',
    'editProfile': 'Edit Profile',
    'changePassword': 'Change Password',
    'oldPassword': 'Old Password',
    'newPassword': 'New Password',
    'save': 'Save Changes',
    'loginToViewPhone': 'Log in to view contact phone',
    'loginRequiredTitle': 'Authentication Required',
    'dontHaveAccount': 'Don\'t have an account? Sign up',
    'alreadyHaveAccount': 'Already have an account? Log in',
    'sortBy': 'Sort by',
    'selectSort': 'Select sorting',
    'ratingDesc': 'Highest Rated',
    'priceAsc': 'Price: Low to High',
    'priceDesc': 'Price: High to Low',
    'bookingDetails': 'Booking Details',
    'paymentSuccess': 'Payment completed successfully!',
    'receiptTitle': 'Payment Receipt',
    'selectDate': 'Select Date',
    'selectTime': 'Select Time Slot',
    'payWith': 'Pay with',
    'paymentMethodLabel': 'Payment Method',
    'bookingHistory': 'My Bookings',
    'invoice': 'Receipt / Invoice',
    'cancelBookingBtn': 'Cancel Booking',
    'status': 'Status',
    'unpaid': 'Unpaid',
    'paid': 'Paid',
    'cancelled': 'Cancelled',
    'ownerPanel': 'Owner Dashboard',
    'myFields': 'My Pitches',
    'addField': 'Add New Pitch',
    'incomingBookings': 'Incoming Bookings',
    'fieldName': 'Pitch Name',
    'fieldNamePlaceholder': 'Enter pitch name',
    'address': 'Address',
    'addressPlaceholder': 'Enter full address',
    'pricePerHour': 'Hourly Rate',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'imageUrl': 'Image URL',
    'saveField': 'Save Pitch',
    'fieldAddedSuccess': 'New pitch added successfully!',
    'noFieldsYet': 'You have not registered any pitches yet.',
    'noIncomingBookings': 'No incoming bookings yet.',
    'shareTelegram': 'Share via Telegram',
    'shareTelegramText': 'Check out this awesome football pitch on Maydonuz:',
    'copyAddress': 'Copy Address',
    'copiedAddress': 'Address copied to clipboard!',
    'copiedSuccess': 'Copied',
    'selectSlotFirst': 'Please choose an available time slot first!',
    'fillRequiredFields': 'Please fill all required fields.',
    'imageTooLarge': 'Image size is too large (max 2MB)',
    'quickTags': 'Quick Picks',
    'all': 'All',
    'topRated': '⭐ 4.5+ Rating',
    'artificialGrass': 'Artificial Turf',
    'affordable': 'Affordable',
    'openInMap': 'Open in Map',
    'details': 'Details & Booking',
    'myBookings': 'My Bookings',
    'profile': 'Profile',
    'navigation': 'Navigation',
    'phoneLoginRequired': 'Phone: Sign up to view',
    'phoneLockNotice': 'Register to unlock phone number',
    'phoneDirectContact': 'Direct communication with pitch owners',
    'guestBannerTitle': 'Book Pitches and View Contact Numbers',
    'guestBannerSubtitle': 'Sign up for free to unlock direct pitch contacts and fast online booking',
    'registerToBookPrompt': 'Sign up to book this pitch',
    'registerToBookSub': 'Sign in to confirm booking and receive instant SMS confirmation',
    'loginToContinue': 'Please log in or register to add your pitch',
    'loadMore': 'Show More',
    'googleMapsNav': 'Directions on Google Maps',
    'cashPayment': 'Cash on Pitch',
    'bookAgain': 'Book Another Pitch',
    'howItWorksBadge': 'Easy & fast in 3 simple steps',
    'howItWorksTitle': 'How does Maydonuz work?',
    'howItWorksSubtitle': 'Find the right pitch, select an open slot, and get into the game in under 1 minute — no phone call hassles.',
    'step1Indicator': '1. Choose Pitch',
    'step2Indicator': '2. Pick Time',
    'step3Indicator': '3. Play Ball',
    'step1Badge': 'Fast Filter',
    'step1Title': '1. Choose a Pitch',
    'step1Desc': 'Search by district, price, pitch type, and amenities (showers, lighting, turf quality).',
    'tryDistrict': 'Try a district:',
    'clickToTest': 'click',
    'step2Badge': 'Live Schedule',
    'step2Title': '2. Select a Slot',
    'step2Desc': 'Check open hours in real time. Reserve immediately with a single tap without delays.',
    'selectSlotHint': 'Click an available slot:',
    'instantConfirm': 'Instant Confirmation',
    'step3Badge': 'Match Pass',
    'step3Title': '3. Play Football!',
    'step3Desc': 'Complete payment via Click, Payme or Cash, share the pass with teammates, and kick off!',
    'matchTicket': 'Match Pass Ticket',
    'matchShare': 'Share with Friends',
    'ticketCopied': 'Shared!',
    'ownerBadge': 'For Pitch Owners & Managers',
    'ownerHeroTitle': 'Own a football pitch? Turn empty hours into revenue',
    'ownerHeroDesc': 'Never let your pitch sit empty. List on Maydonuz, reach thousands of passionate local players, and boost your turnover up to 40%.',
    'ownerCtaPrimary': 'List Your Pitch for Free',
    'ownerFeature1Title': 'Fill Empty Off-Peak Hours',
    'ownerFeature1Desc': 'Attract regular teams even for morning and afternoon off-peak slots.',
    'ownerFeature2Title': 'Automated Booking Calendar',
    'ownerFeature2Desc': 'Manage schedules, bookings, and customer requests from one simple dashboard.',
    'ownerFeature3Title': '0% Commission First Month',
    'ownerFeature3Desc': 'Listing is 100% free with no upfront cost or hidden fees.',
    'revenueCalculatorTitle': 'Revenue Calculator',
    'revenueCalculatorSubtitle': 'Estimate how much additional revenue your pitch could generate on Maydonuz',
    'hourlyPriceLabel': 'Hourly Rate',
    'dailyHoursLabel': 'Avg Daily Booked Hours',
    'hoursPerDay': 'hrs / day',
    'potentialMonthlyIncome': 'Estimated Monthly Revenue',
    'revenueFormulaNote': 'Calculated based on 30-day average monthly occupancy',
    'startEarningToday': 'Start Earning Today',
    'nearestToMe': 'Nearest to Me',
    'sortByDistance': 'Distance: Nearest',
    'distanceFromYou': 'From you',
    'kmAway': 'km',
    'locating': 'Detecting location...',
    'locationFound': 'Location detected!',
    'locationPermissionDenied': 'Geolocation permission denied',
    'yourLocation': 'Your Location'
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: defaultLanguage,
  setLanguage: () => {},
  translations: translations[defaultLanguage],
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  useEffect(() => {
    document.title = translations[language].appName;
  }, [language]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        translations: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
